#!/bin/bash

nodeinfo=$(scontrol show node)
name_regex="NodeName=([a-z]+\-?[0-9]+?)"
cpu_alloc_regex="CPUAlloc=([0-9]+)"
cpu_total_regex="CPUTot=([0-9]+)"
mem_alloc_regex="AllocMem=([0-9]+)"
mem_total_regex="RealMemory=([0-9]+)"

echo -e "Node\t\t\tCPUs(Used)\t\tRAM(Used)"
echo "---------------------------------------------------------"
for node in $nodeinfo; do
	if [[ $node =~ $name_regex ]]; then
		name=${BASH_REMATCH[1]}
	fi
	if [[ $node =~ $cpu_alloc_regex ]]; then
		cpu_alloc=${BASH_REMATCH[1]}
	fi
	if [[ $node =~ $cpu_total_regex ]]; then
		cpu_total=${BASH_REMATCH[1]}
	fi
	if [[ $node =~ $mem_alloc_regex ]]; then
		mem_alloc=${BASH_REMATCH[1]}
		if [[ $1 == "-a" ]] || [[ $cpu_alloc -gt "0" ]]; then
			printf "%18s\t%2d of %2d\t%6d of %6d\n" $name $cpu_alloc $cpu_total $mem_alloc $mem_total
		fi
	fi
	if [[ $node =~ $mem_total_regex ]]; then
		mem_total=${BASH_REMATCH[1]}
	fi
done
